#!/bin/bash
if [ -f .env ]; then
    cp .env .env.example
    # Replace actual values with placeholders
    sed -i '' -E 's/=.*/=/g' .env.example  # For macOS
    # sed -i -E 's/=.*/=/g' .env.example   # Use this on Linux
    echo "Updated .env.example file"
fi

